import imageStyle from './ScrollImage.module.css';
import {useRef, useEffect} from 'react';

const ScrollImage = (props)=>{
    const imageRef = useRef();
    useEffect(()=>{
        const imageRefWidth = imageRef.current.getBoundingClientRect().width
        props.onGetImageRefWidth(imageRefWidth);
    }, [])


    return (
        <div ref={imageRef} className={imageStyle.imageContainer}>
            <img src={props.image} alt="a picture of me generated by dawn AI" />
        </div>
    )
}
export default ScrollImage;